name: snakeobjectsDev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - ipython
  - setuptools
  - pytest-cov
  - sphinx
  - conda-build
  - anaconda-client
  - snakemake-minimal>5.20

