name: snakeobjectsTutorial
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - ipython
  - bcftools=1.3.1
  - bwa=0.7.12
  - graphviz=2.38.0
  - setuptools
  - pytest-cov
  - sphinx
  - conda-build
  - anaconda-client
  - snakemake-minimal>5.20
  - sphinx_rtd_theme
  - pandas
  - matplotlib
  - samtools
  - pysam 
  - pip
  - pip:
    - sphinx-autorun
    - myvariant
